version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
        - ./db/var:/data/db
    ports:
      - "27017:27017"
  api:
    image: node:latest
    container_name: youdescribe-api
    restart: always
    command: node /usr/src/app/index.js
    environment:
      NODE_ENV: dev
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
